name: Build and deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main 

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Debug AWS Credentials
        run: aws sts get-caller-identity


      - name: Deploy to server
        uses: bitovi/github-actions-deploy-docker-to-ec2@main
        with:
          checkout: false
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_resource_identifier: ${{ secrets.EC2_RESOURCE_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          app_port: 5000
          tf_state_bucket: niallroche-cs0201-ci-cd-main-tf-state-new
